# Generated by Django 5.2.15 on 2026-06-27 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_goodsreceipt_received_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective'), ('DAMAGED', 'Damaged in Transit'), ('WRONG_ITEM', 'Wrong Item'), ('EXPIRED', 'Expired'), ('OVERSTOCK', 'Overstock'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('restocked', models.BooleanField(default=False, help_text='Has the returned item been restocked?')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='suppliers.purchaseorder')),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason_detail', models.TextField(blank=True)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.purchaseorderitem')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchasereturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
