# Generated by Django 5.2.15 on 2026-06-06 03:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning')], default='AVAILABLE', max_length=20)),
                ('pos_x', models.PositiveIntegerField(default=0)),
                ('pos_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='organisation.floor')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('floor', 'name'), name='unique_table_per_floor')],
            },
        ),
    ]
