# Generated by Django 5.2.15 on 2026-06-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_tablesession_is_billed_tablesession_total_amount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tablesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('table',), name='unique_open_session_per_table'),
        ),
    ]
