# Generated by Django 5.2.15 on 2026-06-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_tablesession_unique_open_session_per_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('SQUARE', 'Square'), ('ROUND', 'Round'), ('RECTANGLE', 'Rectangle'), ('BOOTH', 'Booth')], default='SQUARE', max_length=20),
        ),
    ]
