# Generated by Django 5.2.6 on 2026-07-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary in NPR', max_digits=12),
        ),
    ]
