# Generated by Django 5.2.15 on 2026-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('menu', '0002_modifiergroup_taxcategory_alter_menucategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_days',
            field=models.CharField(blank=True, help_text='Comma-separated: MON,TUE,WED', max_length=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_items',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_first_order_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_new_customer_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_items_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='stackable',
            field=models.BooleanField(default=False, help_text='Can be combined with other coupons'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit_per_customer',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('BOGO', 'Buy One Get One'), ('FREE_DELIVERY', 'Free Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
