# Generated by Django 5.2.15 on 2026-06-27 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('reservations', '0002_reservation_reminder_sent_waitlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(blank=True, help_text='phone, website, walk-in, third-party', max_length=50),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='estimated_wait_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
