# Generated by Django 5.2.15 on 2026-06-27 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_orderitem_unique_menu_item_per_order'),
        ('organisation', '0007_table_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='KDSDisplay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('SERVED', 'Served')], default='PENDING', max_length=20)),
                ('display_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kds_entries', to='organisation.branch')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kds_entry', to='orders.order')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
