# Generated by Django 5.2.15 on 2026-06-27 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds', '0001_initial'),
        ('orders', '0005_alter_order_order_number'),
        ('organisation', '0007_table_shape'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kdsdisplay',
            options={'ordering': ['-is_urgent', 'priority', 'created_at']},
        ),
        migrations.AddField(
            model_name='kdsdisplay',
            name='alert_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Alert if not started within N minutes'),
        ),
        migrations.AddField(
            model_name='kdsdisplay',
            name='assigned_cook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kdsdisplay',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kdsdisplay',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='KDSItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('menu_item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('kds_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_items', to='kds.kdsdisplay')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_status', to='orders.orderitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KDSStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_stations', to='organisation.branch')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='kdsdisplay',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displays', to='kds.kdsstation'),
        ),
    ]
