# Generated by Django 5.2.15 on 2026-06-27 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('STAFF', 'Staff'), ('FINANCIAL', 'Financial'), ('CUSTOMER', 'Customer'), ('OPERATIONS', 'Operations')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('query_config', models.JSONField(default=dict, help_text='Report query parameters as JSON')),
                ('default_format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('EXCEL', 'Excel'), ('HTML', 'HTML')], default='CSV', max_length=10)),
                ('is_system', models.BooleanField(default=False, help_text='Pre-installed report')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('EXCEL', 'Excel'), ('HTML', 'HTML')], max_length=10)),
                ('file', models.FileField(blank=True, upload_to='reports/exports/')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('EXCEL', 'Excel'), ('HTML', 'HTML')], default='CSV', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
