# Generated by Django 5.2.15 on 2026-06-27 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0007_table_shape'),
        ('payroll', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.leavetype'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.leavetype'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='organisation.branch'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='payslipallowance',
            name='allowance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.allowancetype'),
        ),
        migrations.AddField(
            model_name='payslipallowance',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payroll.payslip'),
        ),
        migrations.AddField(
            model_name='payslipdeduction',
            name='deduction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.deductiontype'),
        ),
        migrations.AddField(
            model_name='payslipdeduction',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payslip'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='staff.staffprofile'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('staff', 'leave_type', 'year'), name='unique_leave_balance'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('staff', 'period'), name='unique_payslip_per_staff_period'),
        ),
    ]
